@startuml
skinparam monochrome true

Title State machine for an invoice

[*] --> Created
Created --> ExternalProcessing : T1
Created --> Rejected : T2
Created --> Revoked : T3

ExternalProcessing --> Pending : T4

Pending --> Expired : T5
Pending --> Deleted : T6
Pending --> Approved : T7
Pending --> Revoked : T8
Approved --> Approved : T9
Approved --> Pending : T10
Approved --> Deleted : T11
Expired --> [*]
Revoked --> [*]
Deleted --> [*]
Rejected --> [*]

Pending : - ExternalID
Approved : - Amount\n- Due
Rejected : - Problems

note bottom of Approved
    Final state.
    Not verifiable
end note

@enduml